version: 0.2

env:
  variables:
    AWS_REGION: us-east-1                           # 🟢 Change this to your AWS region
    IMAGE_REPO_NAME: car-service/user-service        # 🟢 Your ECR repository name
    IMAGE_TAG: latest                               # Use 'latest' or '$CODEBUILD_RESOLVED_SOURCE_VERSION' for commit hash
    CONTAINER_NAME: user-management-container       # 🟢 Container name for ECS task definition
    GO_VERSION: "1.25"                              # Go version

phases:
  install:
    runtime-versions:
      golang: 1.25                                  # Use Go runtime                              # Docker for building images
    commands:
      - echo "[+] Installing dependencies..."
      - go version
      - docker --version

  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo $DOCKERHUB_USERNAME
      - echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - echo "[+] Starting pre-build phase..."
      - echo "[+] Running Go tests..."
      - go test -v ./... || echo "Tests not configured yet"
      - echo "[+] Getting AWS account ID..."
      - ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
      - ECR_URI=$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - echo "[+] Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_URI
      - echo "[+] Checking if ECR repository exists..."
      - |
        if ! aws ecr describe-repositories --repository-names $IMAGE_REPO_NAME --region $AWS_REGION > /dev/null 2>&1; then
          echo "[!] ECR repository not found — creating $IMAGE_REPO_NAME..."
          aws ecr create-repository \
            --repository-name $IMAGE_REPO_NAME \
            --region $AWS_REGION \
            --image-scanning-configuration scanOnPush=true \
            --encryption-configuration encryptionType=AES256
          echo "[+] ECR repository created successfully"
        else
          echo "[+] ECR repository already exists"
        fi

  build:
    commands:
      - echo "[+] Building Docker image..."
      - echo "[+] Using Dockerfile at Docker/Dockerfile"
      - docker build -f Docker/Dockerfile -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - echo "[+] Tagging Docker image for ECR..."
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $ECR_URI/$IMAGE_REPO_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo "[+] Pushing Docker image to ECR..."
      - docker push $ECR_URI/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo "[+] Docker images pushed successfully"
      - echo "[+] Image URI - $ECR_URI/$IMAGE_REPO_NAME:$IMAGE_TAG"
      - echo "[+] Generating imagedefinitions.json for ECS deployment..."
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $ECR_URI/$IMAGE_REPO_NAME:$IMAGE_TAG > imagedefinitions.json
      - echo "[+] Contents of imagedefinitions.json:"
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
  name: BuildArtifact

cache:
  paths:
    - '/go/pkg/mod/**/*'                           # Cache Go modules for faster builds